const GEMINI_API_KEY = process.env.GEMINI_API_KEY!;
const NEXT_PUBLIC_API_URL = process.env.NEXT_PUBLIC_API_URL!;
const SUPABASE_URL = process.env.SUPABASE_URL!;
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY!;
const GROQ_API_KEY = process.env.GROQ_API_KEY!;
const CRON_SECRET = process.env.CRON_SECRET!;

export {
  GEMINI_API_KEY,
  NEXT_PUBLIC_API_URL,
  SUPABASE_URL,
  SUPABASE_ANON_KEY,
  GROQ_API_KEY,
  CRON_SECRET,
};
