import { TechType } from "./types";

const tech: TechType[] = [
  {
    id: 1,
    name: "React",
    isBeginner: false,
    description: "JavaScript library for building user interfaces.",
    img: "/skills/react.svg",
  },
  {
    id: 2,
    name: "Node.js",
    isBeginner: false,
    description: "JavaScript runtime for server-side applications.",
    img: "/skills/nodejs.svg",
  },
  {
    id: 3,
    name: "Express.js",
    isBeginner: false,
    description: "Minimal web framework for Node.js.",
    img: "/skills/express.svg",
  },
  {
    id: 4,
    name: "MongoDB",
    isBeginner: false,
    description: "NoSQL database for scalable applications.",
    img: "/skills/mongodb.svg",
  },
  {
    id: 5,
    name: "Next.js",
    isBeginner: false,
    description: "React framework for server-side rendering and static sites.",
    img: "/skills/next.svg",
  },
  {
    id: 6,
    name: "Fastify",
    isBeginner: false,
    description: "High-performance web framework for Node.js.",
    img: "/skills/fastify.svg",
  },
  {
    id: 7,
    name: "Turso",
    isBeginner: false,
    description: "Serverless SQLite database for edge applications.",
    img: "/skills/turso.svg",
  },
  {
    id: 8,
    name: "Redis",
    isBeginner: false,
    description: "In-memory store for caching and message brokering.",
    img: "/skills/redis.svg",
  },
  {
    id: 9,
    name: "React Native",
    isBeginner: false,
    description: "Framework for building mobile apps with React.",
    img: "/skills/react-native.svg",
  },
  {
    id: 10,
    name: "TypeScript",
    isBeginner: false,
    description: "Typed superset of JavaScript.",
    img: "/skills/typescript.svg",
  },
  {
    id: 11,
    name: "JavaScript",
    isBeginner: false,
    description: "Programming language for web development.",
    img: "/skills/javascript.svg",
  },
  {
    id: 12,
    name: "GraphQL",
    isBeginner: true,
    description: "Query language for APIs.",
    img: "/skills/graphql.svg",
  },
  {
    id: 13,
    name: "Python",
    isBeginner: false,
    description: "Versatile programming language for various applications.",
    img: "/skills/python.svg",
  },
  {
    id: 14,
    name: "PineconeDB",
    isBeginner: true,
    description: "Vector database for machine learning.",
    img: "/skills/pinecone.svg",
  },
  {
    id: 15,
    name: "Supabase",
    isBeginner: true,
    description: "Open-source backend-as-a-service with PostgreSQL.",
    img: "/skills/supabase.svg",
  },
  {
    id: 16,
    name: "HTML",
    isBeginner: false,
    description: "Markup language for web content.",
    img: "/skills/html5.svg",
  },
  {
    id: 17,
    name: "CSS",
    isBeginner: false,
    description: "Stylesheet language for web design.",
    img: "/skills/css3.svg",
  },
  {
    id: 18,
    name: "Tailwind",
    isBeginner: false,
    description: "Utility-first CSS framework.",
    img: "/skills/tailwind.svg",
  },
  {
    id: 19,
    name: "Expo",
    isBeginner: false,
    description: "Toolchain for building React Native apps.",
    img: "/skills/expo.svg",
  },
];

export { tech };
